name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        activate-environment: pfapack-env
        architecture: ${{ matrix.os == 'macos-latest' && 'arm64' || 'x64' }}

    - name: Cache Conda packages
      uses: actions/cache@v4
      with:
        path: ~/miniconda3/pkgs
        key: ${{ runner.OS }}-conda-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.OS }}-conda-

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y numpy scipy pytest
        conda install -y -c conda-forge compilers
        pip install wheel setuptools twine
        pip install -r requirements.txt

    - name: Build package
      shell: bash -l {0}
      run: |
        python setup.py sdist bdist_wheel

    - name: Run tests
      shell: bash -l {0}
      run: pytest -v tests

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/

  publish:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Prepare distribution files
      run: |
        mkdir combined_dist
        find dist -name '*.whl' -exec cp {} combined_dist/ \;
        cp dist/dist-ubuntu-latest-3.9/*.tar.gz combined_dist/

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        pip install twine
        twine upload combined_dist/*

    - name: Debug information
      if: failure()
      run: |
        conda list
        pip list
        env
        top -l 1 | head -n 10
        ps aux
